#!/usr/bin/env python3

import sys, re
sys.path.append("3rdparty/edrefcard")

from bindingsData import *

outFilename = 'refcard/configs/generatedDevices.yaml'

outFile = open(outFilename, "w")
outFile.write('''#################################################################
### GENERATED BY generateControllerInputs.py - DO NOT MODIFY. ###
#################################################################
---
''')

for name in supportedDevices :
    group = supportedDevices[name]
    image = group['Template']
    devices = group['HandledDevices']
    outFile.write('{n}:\n'.format(n=name))
    outFile.write('  Image: {i}.jpg\n'.format(i=image))
    outFile.write('  Devices:\n')
    for device in devices:
        if device == 'Keyboard':
            continue
        outFile.write('    {d}:\n'.format(d=device))
        displayName = device
        if 'displayName' in hotasDetails[device]:
            displayName = hotasDetails[device]['displayName']
        outFile.write('      DisplayName: {dn}\n'.format(dn=displayName))
        outFile.write('      Inputs:\n')
        
        for key in hotasDetails[device]:
            if key == 'displayName':
                continue
            shortKey = re.sub('^Joy_', '', key)
            outFile.write('        {k}:\n'.format(k=shortKey))
            data = hotasDetails[device][key]
            if data['Type'] == 'Digital':
                outFile.write('          IsDigital: true\n')
            else:
                outFile.write('          IsDigital: false\n')
            outFile.write('          OffsetX: {x}\n'.format(x=data['x']))
            outFile.write('          OffsetY: {y}\n'.format(y=data['y']))
            outFile.write('          Width: {w}\n'.format(w=data['width']))
            if 'height' in data:
                outFile.write('          Height: {h}\n'.format(h=data['height']))
            else:
                outFile.write('          Height: 54\n')
    outFile.write('\n')
outFile.write('''...''')

outFile.close()
